# -*- coding: utf-8 -*-
"""Cambio envidioso

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pq0lmtGYVdqEzbnjOGp0SqfYRrK6iabR
"""

def cambio_greedy(cantidad, denominaciones):
    denominaciones = sorted(denominaciones, reverse=True)  # Denominaciones deben estar ordenadas de mayor a menor
    resultado = []  # aquí debe aparecerme el tipo de moneda post cuantas veces me dan ese tipo de moneda [50,1]

    for moneda in denominaciones:
        if cantidad <= 0:
            break

        if cantidad >= moneda:
            num = cantidad // moneda
            cantidad = cantidad - num * moneda
            resultado.append([moneda, num])

    if cantidad > 0:
        print("No te puedo dar un cambio exacto con las denominaciones que me diste.")

    return resultado


# Pruebas      #cantidad   #Las monedas de cambio
print(cambio_greedy(2452, [500, 200, 100, 50, 20, 5, 1]))
print(cambio_greedy(99, [50, 20, 5, 1]))
print(cambio_greedy(99, [5, 20, 1, 50]))  # No ordenado