# -*- coding: utf-8 -*-
"""contraseña bruta

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wy7bevjK2VbAzmMOzKX5XXVGf5EK0xZa
"""

from string import ascii_letters, digits
from itertools import product
from time import time

def buscador_fuerza_bruta(contrasena_objetivo):
    caracteres = ascii_letters + digits
    longitud = len(contrasena_objetivo)

    if longitud not in [4, 8, 10]:
        print("La contraseña debe tener solamente y unicamente 4, 8 o 10 caracteres")
        return

    archivo = open("combinaciones.txt", "w")

    for comb in product(caracteres, repeat=longitud):
        prueba = "".join(comb)
        archivo.write(prueba + "\n")
        if prueba == contrasena_objetivo:
            print(f"Contraseña encontrada: {prueba}")
            break
    archivo.close()

# Ejecución
t0 = time()
contrasena = "Alan"  # Aqui está hecho para que pueda elegir contraseñas de 4 8 o 10 digitos
buscador_fuerza_bruta(contrasena)
print(f"Tiempo que tarda en ejecutarse: {round(time() - t0, 6)} segundos")