# -*- coding: utf-8 -*-
"""ORDENAMIENTO SHORT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eMs0msck1CLUtOvF-eO8vqVjQi6I6oly
"""

def insertion_sort(lista):
    for i in range(1, len(lista)):
        actual = lista[i]
        posicion = i
        print(f"Valor a ordenar = {actual}")

        while posicion > 0 and lista[posicion - 1] > actual:
            lista[posicion] = lista[posicion - 1]
            posicion -= 1

        lista[posicion] = actual
        print(lista)
        print()
    return lista

# Ejemplo de uso
lista = [21, 10, 0, 11, 9, 24, 20, 14, 1]
print(f"Lista original: {lista}")
lista_ordenada = insertion_sort(lista)
print(f"Lista ya ordenada: {lista_ordenada}")