# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKt4eRLD2RgzuxwD8aGOO9FnjorLto67
"""

# Inicializando variables
x = 10  # variable de tipo entero
print(x)

cadena = "Hola Mundo"  # variable de tipo cadena
print(cadena)

# Asigna un mismo valor a tres variables
x = y = z = 10
print(x, y, z)

# La función type() permite conocer el tipo de una variable
print(type(x))
print(type(cadena))

# Se pueden cambiar los valores de las variables y el tipo se cambia automáticamente
x = "Hola Mundo"
cadena = 10
print(type(x))
print(type(cadena))

# Variables constantes (por convención en mayúsculas)
SEGUNDOS_POR_DIA = 60 * 60 * 24
PI = 3.14
print(f"Segundos por día: {SEGUNDOS_POR_DIA}")