# -*- coding: utf-8 -*-
"""11. Estructuras de Control Repetitivas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKt4eRLD2RgzuxwD8aGOO9FnjorLto67
"""

# Ciclo while - Ejemplo 1
def cuenta(limite):
    i = limite
    while True:
        print(i)
        i = i - 1
        if i == 0:
            break  # Rompiendo el ciclo

cuenta(5)

# Ciclo while - Ejemplo 2
def factorial(n):
    i = 2
    tmp = 1
    while i < n + 1:
        tmp = tmp * i
        i = i + 1
    return tmp

print(factorial(4))
print(factorial(6))

# Ciclo for - Iteración en listas
for x in [1, 2, 3, 4, 5]:
    print(x)

# La función range() sirve para generar una lista
for x in range(5):  # Equivalente a range(0,5)
    print(x)

# También se puede inicializar desde números negativos
for x in range(-5, 2):
    print(x)

for num in ["uno", "dos", "tres", "cuatro"]:
    print(num)

# Iteración en diccionarios
elementos = {'hidrogeno': 1, 'helio': 2, 'carbon': 6}

for llave, valor in elementos.items():
    print(llave, " = ", valor)

# Obteniendo sólo las llaves
for llave in elementos.keys():
    print(llave)

# Obteniendo sólo los valores
for valor in elementos.values():
    print(valor)

# Usando enumerate para obtener índice
for idx, x in enumerate(elementos):
    print("El índice es: {} y el elemento: {}".format(idx, x))

# Else en ciclos for
def cuenta_idiom(limite):
    for i in range(limite, 0, -1):
        print(i)
    else:  # Corresponde al for, NO al IF
        print("Cuenta finalizada")

cuenta_idiom(3)

# Else no se ejecuta si se rompe el ciclo
def cuenta_idiomv2(limite):
    for i in range(limite, 0, -1):
        print(i)
        if i == 3:
            break  # rompe el ciclo
    else:  # Corresponde al FOR, NO al IF
        print("Cuenta finalizada")

cuenta_idiomv2(5)