# -*- coding: utf-8 -*-
"""12. Uso de Bibliotecas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKt4eRLD2RgzuxwD8aGOO9FnjorLto67
"""

import math

# Una vez que la biblioteca está importada, se pueden conocer las funciones que éste contiene
print(dir(math))
# Para conocer cómo utilizar las funciones, se puede utilizar la función help
# help(math.log)
# Se puede definir un alias para llamar a las funciones
import math as ma

x = ma.cos(ma.pi)
print(x)

# Usando funciones específicas de math
print("Pi:", math.pi)
print("Raíz cuadrada de 16:", math.sqrt(16))
print("Factorial de 5:", math.factorial(5))