# -*- coding: utf-8 -*-
"""13- GRAFICACION

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKt4eRLD2RgzuxwD8aGOO9FnjorLto67
"""

# Importando las bibliotecas
import matplotlib.pyplot as plt
from numpy import linspace, sin

# Datos de entrada
x = linspace(0, 5, 20)  # Generando 20 puntos entre 0 y 5

fig, ax = plt.subplots(facecolor='w', edgecolor='k')

ax.plot(x, sin(x), marker="o", color="r", linestyle='None')

ax.grid(True)
ax.set_xlabel('X')      # Etiqueta del eje x
ax.set_ylabel('Y')      # Etiqueta del eje y
ax.grid(True)
ax.legend(["y = sin(x)"])

plt.title('Puntos')
plt.show()

fig.savefig("grafica.png")  # Guardando la gráfica

