# -*- coding: utf-8 -*-
"""14. Ejemplo de Entrada de Datos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKt4eRLD2RgzuxwD8aGOO9FnjorLto67
"""

# Se pide el nombre al usuario
print("Hola, ¿cómo te llamas?")
# Se leen los datos introducidos por el usuario y se asignan a la variable nombre
nombre = input()
# Se escribe el nombre solicitado
print("Buen día {}".format(nombre))
print("--Calculadora--") #Opciones para el usuario
print("1- Sumar")
print("2- Restar")
print("3- Multiplicar")
print("4- Dividir")
print("5- Salir")

# Se solicita que el usuario especifique alguna operación
op = int(input('Opcion: '))

