# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKt4eRLD2RgzuxwD8aGOO9FnjorLto67
"""

# Inicializando cadenas
cadena1 = 'Hola'
cadena2 = "Mundo"
print(cadena1)
print(cadena2)

# Concatenación de cadenas
concat_cadenas = cadena1 + " " + cadena2
print(concat_cadenas)

# Para concatenar un número y una cadena se debe usar la función str()
num_cadena = concat_cadenas + ' ' + str(3)
print(num_cadena)

# Uso de format() - método recomendado
num_cadena = "{} {} {}".format(cadena1, cadena2, 3)
print(num_cadena)

# Cambiando el orden con format()
num_cadena = "Cambiando el orden: {1} {2} {0}".format(cadena1, cadena2, 3)
print(num_cadena)