# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKt4eRLD2RgzuxwD8aGOO9FnjorLto67
"""

# Operadores aritméticos
print(1 + 5)
print(6 - 3)
print(10 - 4)
print(100 / 50)
print(10 % 2)
print(((20 * 3) + (10 + 1)) / 10)
print(2 ** 2)

# Operadores booleanos
print(False and True)
print(True or False)
print(not True)

# Operadores de comparación
print(7 < 5)  # False
print(7 > 5)  # True
print((11 * 3) + 2 == 36 - 1)  # True
print((11 * 3) + 2 >= 36)  # False
print("curso" != "CuR80")  # True