# -*- coding: utf-8 -*-
"""5. Tuplas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKt4eRLD2RgzuxwD8aGOO9FnjorLto67
"""

# Declaración de una tupla
tupla_diasDelMes = (31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)
print(tupla_diasDelMes)     # Imprimir la tupla completa
print(tupla_diasDelMes[0])  # Imprimir elemento 1
print(tupla_diasDelMes[3])  # Imprimir elemento 4
print(tupla_diasDelMes[1])  # Imprimir elemento 2

# Declaración de tuplas anidadas
tupla_numeros = (('cero', 0), ('uno', 1, 'UNO'), ('dos', 2), ('tres', 3), ('cuatro', 4), ('X', 5))
print(tupla_numeros)        # imprimir tupla completa
print(tupla_numeros[0])     # imprime el elemento 0 de la tupla
print(tupla_numeros[1])     # imprime el elemento 1 de la tupla
print(tupla_numeros[2][0])  # imprime el primer elemento de la tupla en la posición 2
print(tupla_numeros[2][1])  # imprime el segundo elemento de la tupla en la posición 2
print(tupla_numeros[1][0])
print(tupla_numeros[1][1])
print(tupla_numeros[1][2])

# Probando la mutabilidad de las listas vs la no mutabilidad de las tuplas
print("valor actual {}".format(lista_diasDelMes[0]))
lista_diasDelMes[0] = 50
print("valor cambiado {}".format(lista_diasDelMes[0]))