# -*- coding: utf-8 -*-
"""6- Tuplas con Nombre

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKt4eRLD2RgzuxwD8aGOO9FnjorLto67
"""

from collections import namedtuple

# Se crea la tupla con nombre
planeta = namedtuple('planeta', ['nombre', 'numero'])

# Se crea el planeta 1 y se agregan a la tupla los valores correspondientes a los campos
planeta1 = planeta('Mercurio', 1)
print(planeta1)

# Se crea el planeta 2
planeta2 = planeta('Venus', 2)

# Se imprimen los valores de los campos
print(planeta1.nombre, planeta1.numero)
print(planeta2[0], planeta2[1])

print('Campos de la tupla: {}'.format(planeta1._fields))