# -*- coding: utf-8 -*-
"""7. Diccionarios

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKt4eRLD2RgzuxwD8aGOO9FnjorLto67
"""

# Creando un diccionario
elementos = {'hidrogeno': 1, 'helio': 2, 'carbon': 6}

print(elementos)
print(elementos['hidrogeno'])

# Se pueden agregar elementos al diccionario
elementos['litio'] = 3
elementos['nitrogeno'] = 8
print(elementos)

# Creando un nuevo diccionario
elementos2 = {}
elementos2['H'] = {'name': 'Hydrogen', 'number': 1, 'weight': 1.00794}
elementos2['He'] = {'name': 'Helium', 'number': 2, 'weight': 4.002602}
print(elementos2)

# Imprimiendo los datos de un elemento del diccionario
print(elementos2['H'])
print(elementos2['H']['name'])
print(elementos2['H']['number'])
elementos2['H']['weight'] = 4.30  # Cambiando el valor de un elemento
print(elementos2['H']['weight'])

# Agregando elementos a una llave
elementos2['H'].update({'gas noble': True})
print(elementos2['H'])

# Mostrando todos los elementos del diccionario
print(elementos2.items())

# Mostrando todas las llaves del diccionario
print(elementos2.keys())