# -*- coding: utf-8 -*-
"""8. Funciones

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKt4eRLD2RgzuxwD8aGOO9FnjorLto67
"""

# Las funciones pueden recibir n número de parámetros
def imprime_nombre(nombre):
    print("hola " + nombre)

# Llamada a la función
imprime_nombre("Alan Juarez")

# Definiendo una función que regresa el cuadrado de un número
def cuadrado(x):
    return x ** 2

x = 5
print("El cuadrado de {} es {}".format(x, cuadrado(x)))

# Definiendo una función que regrese más de un valor
def varios(x):
    return x ** 2, x ** 3, x ** 4

# Los valores que regresa la función pueden ser guardado en variables separadas por ,
val1, val2, val3 = varios(2)
print("{} {} {}".format(val1, val2, val3))

# Función con un parámetro con un valor por defecto
def cuadrado_default(x=3):
    return x ** 2

print(cuadrado_default())  # Usa el valor por defecto
print(cuadrado_default(5)) # Usa el valor proporcionado

# Usando el operador '_' para ignorar valores
val4, _, val5 = varios(2)
print("{} {}".format(val4, val5))