# -*- coding: utf-8 -*-
"""9- Variables Globales

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKt4eRLD2RgzuxwD8aGOO9FnjorLto67
"""

# Se crea una variable en el espacio global de nombres
vg = 'Global'

# Se crea una función que imprime la variable global
def function_v1():
    print(vg)

# Llamada a la función que imprime la variable global
function_v1()
print(vg)

# Se crea una variable local que tiene el mismo nombre que la variable global
def function_v2():
    vg = "Local"
    print(vg)

function_v2()
print(vg)  # Sigue imprimiendo "Global"

# Usando global para modificar la variable global
def function_v4():
    global vg
    print(vg)
    vg = "Local"
    print(vg)

function_v4()
print(vg)