# -*- coding: utf-8 -*-
"""FIBONACHI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKt4eRLD2RgzuxwD8aGOO9FnjorLto67
"""

memoria = {1: 0, 2: 1}

def fibonacci(x):
    if x in memoria:
        return memoria[x]
    memoria[x] = fibonacci(x-1) + fibonacci(x-2)
    return memoria[x]

# Posiciones
posiciones = [7, 21, 40, 71, 94]

print("==== Valores de la sucesion de Fibonacci: ====")
for p in posiciones:
    print(f"F({p}) = {fibonacci(p)}")

