# -*- coding: utf-8 -*-
"""BUTAMOP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pq0lmtGYVdqEzbnjOGp0SqfYRrK6iabR
"""

import time

def fibonachiBUP(n):
    if not isinstance(n, int):
        raise TypeError("n debe ser un entero >= 0")
    if n < 0:
        raise ValueError("n debe ser >= 0")

    if n == 0:
        return 0
    if n == 1:
        return 1

    f = [0, 1]  # f[0]=0, f[1]=1
    while len(f) <= n:
        f.append(f[-1] + f[-2])
    return f[n]

def main():
    Pruebas = [0, 1, 2, 5, 10, 20, 30]
    print("Bottom-up DEL FIBONACHI")
    for t in Pruebas:
        t0 = time.perf_counter()
        val = fibonachiBUP(t)
        t1 = time.perf_counter()
        print(f"F({t}) = {val}  (tiempo: {(t1-t0)*1000:.4f} ms)")

if __name__ == "__main__":
    main()