# -*- coding: utf-8 -*-
"""CUIKSHORT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pq0lmtGYVdqEzbnjOGp0SqfYRrK6iabR
"""

import random
import time

def quicksort(lista):
    if not isinstance(lista, list):
        raise TypeError("quicksort espera una lista")
    if len(lista) <= 1:
        return lista[:]
    arr = lista[:]

    def partir(inicio, fin):
        pivot = arr[inicio]
        lft = inicio + 1
        rig = fin

        while True:
            while lft <= rig and arr[lft] <= pivot:
                lft += 1
            while rig >= lft and arr[rig] >= pivot:
                rig -= 1

            if rig < lft:
                break
            else:
                arr[lft], arr[rig] = arr[rig], arr[lft]

        # colocar pivote en su posición correcta
        arr[inicio], arr[rig] = arr[rig], arr[inicio]
        return rig

    def quicksortau(inicio, fin):
        if inicio < fin:
            p = partir(inicio, fin)
            quicksortau(inicio, p - 1)
            quicksortau(p + 1, fin)

    quicksortau(0, len(arr)-1)
    return arr

def main():
    random.seed(0)
    tests = [
        [],
        [1],
        [2, 1],
        [5, 3, 8, 1, 2],
        [random.randint(0, 1000) for _ in range(1000)]
    ]
    print("Quicksort (Divide & Conquer)")
    for i, t in enumerate(tests):
        p0 = time.perf_counter()
        pram = quicksort(t)
        p1 = time.perf_counter()
        ok = pram == sorted(t)
        print(f"Test {i}: len={len(t)}  OK={ok}  tiempo={(p1-p0)*1000:.4f} ms")

if __name__ == "__main__":
    main()